[build-system]
requires = ["maturin>=0.13,<2.0"]
build-backend = "maturin"

[project]
name = "automata_builder"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "numpy",
    "overrides",
    "result",
    "frozendict",
]
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "."
module-name = "automata_builder._rust"
include = ["automata_builder/*.pyi"]
